# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Start"
  url = "#about"
  weight = 10

[[main]]
  name = "Blog"
  url = "#posts"
  weight = 40

#[[main]]
#  name = "Projects"
#  url = "#projects"
#  weight = 30

#[[main]]
#  name = "Publications"
#  url = "#featured"
#  weight = 20

[[main]]
  name  = "Unterricht"
#  url = "unterricht"
  identifier = "unterricht"
  weight = 50

[[main]]
  name = "Allgemeine Informationen"
  url = "unterricht/informationen"
  parent = "unterricht"


[[main]]
  name = "Deutsch"
  url = "unterricht/deutsch"
  parent = "unterricht"

#  [[menu.deutsch]]
#    name = "test"
#    url = "unterricht/deutsch/"

[[main]]
  name = "Politik/Wirtschaft"
  url = "unterricht/politik"
  parent = "unterricht"

#[[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 60

[[main]]
  name ="Literatur"
  url ="literatur/"
  weight = 70


[[main]]
  name ="Fotografie"
#    url ="fotografie"
  identifier = "foto"
  weight = 70

[[main]]
  name = "Ausrüstung"
  url = "fotografie/"
  weight = 70
  parent = "foto"

[[main]]
  name = "Tourenberichte"
  url = "#fototouren"
  weight = 80
  parent = "foto"


[[main]]
    name ="Impressum"
    url ="impressum"
    weight = 80

[[main]]
    name ="Datenschutzerklärung"
    url ="datenschutz"
    weight = 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
